#!/usr/bin/env python3
"""Write THIRD_PARTY_NOTICES.md: the third-party code dino-cloud builds on, and its licenses.

    scripts/third-party.py            # after changing dependencies; commit the result

The Rust crates come from `cargo metadata` (what Cargo.lock resolves for this workspace).
"""
import json, os, re, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "THIRD_PARTY_NOTICES.md")

def rust_crates():
    meta = json.loads(subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--locked"],
        cwd=ROOT, capture_output=True, text=True, check=True).stdout)
    ours = set(meta["workspace_members"])
    rows = []
    for p in meta["packages"]:
        # Ours: this workspace, and crates from this repository's crates/ (no source = a path).
        if p["id"] in ours or p.get("source") is None:
            continue
        rows.append((p["name"], p["version"], p.get("license") or "see its repository", p.get("repository") or ""))
    return sorted(rows, key=lambda r: (r[0].lower(), r[1]))


def main():
    out = ["# Third-party notices", "",
           "dino-cloud is MIT licensed (see [LICENSE](../LICENSE)). It builds on the open source code below,",
           "under those projects' own licenses. Generated by `scripts/third-party.py`."]
    crates = rust_crates()
    out += ["", f"## Rust crates ({len(crates)})", "",
            "Each crate's full license text is in its source, on crates.io and in its repository.", "",
            "| Crate | Version | License |", "| --- | --- | --- |"]
    for name, version, lic, repo in crates:
        label = f"[{name}]({repo})" if repo else name
        out.append(f"| {label} | {version} | {lic} |")
    open(OUT, "w").write("\n".join(out) + "\n")
    print(f"wrote {OUT}: {len(crates)} crates")


main()
