#!/usr/bin/env python3
"""Write THIRD_PARTY_NOTICES.md: the third-party code dino ships, and its licenses.

    scripts/third-party.py            # after changing dependencies; commit the result

The Rust crates come from `cargo metadata` (what Cargo.lock resolves for this workspace), the app's
packages from app/Package.swift, and the files dino carries itself are listed by hand below.
"""
import json, os, re, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "THIRD_PARTY_NOTICES.md")

# Code dino includes as files, beside its packages: (what, where in this repository, license).
BUNDLED = [
    ("Ghostty's shell integration (bash, zsh)", "crates/dino-daemon/shell-integration/", "MIT, see LICENSE-libghostty-spm there"),
    ("bash-preexec", "crates/dino-daemon/shell-integration/bash/bash-preexec.sh", "MIT, see LICENSE-bash-preexec.md there"),
    ("Ghostty 1.3.1's shell integration (fish, elvish, nushell)", "crates/dino-daemon/shell-integration/{fish,elvish,nushell}/", "MIT, see LICENSE-ghostty there"),
    ("Ghostty's terminfo entries (xterm-ghostty, ghostty), for dinod's shells", "crates/dino-daemon/terminfo/", "MIT, see LICENSE-ghostty there"),
    ("Ghostty's terminfo entries (xterm-ghostty, ghostty), for the app's panes", "app/Sources/DinoGhostty/Resources/terminfo/", "MIT, see LICENSE-ghostty there"),
    ("GhosttyTerminal, libghostty-spm's Swift wrapper (as the module DinoGhostty)", "app/Sources/DinoGhostty/", "MIT, see LICENSE there"),
    ("Ghostty 1.3.1's color themes, from iTerm2-Color-Schemes", "app/Sources/DinoGhostty/Resources/Ghostty/themes/", "MIT (the collection; each theme's copyright is its author's), see LICENSE-themes beside it"),
]


def swift_packages():
    text = open(os.path.join(ROOT, "app", "Package.swift")).read()
    return re.findall(r'\.package\(url: "([^"]+)", exact: "([^"]+)"\)', text)


def rust_crates():
    meta = json.loads(subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--locked"],
        cwd=ROOT, capture_output=True, text=True, check=True).stdout)
    ours = set(meta["workspace_members"])
    rows = []
    for p in meta["packages"]:
        if p["id"] in ours:
            continue
        rows.append((p["name"], p["version"], p.get("license") or "see its repository", p.get("repository") or ""))
    return sorted(rows, key=lambda r: (r[0].lower(), r[1]))


def main():
    out = ["# Third-party notices", "",
           "dino is MIT licensed (see [LICENSE](LICENSE)). It includes and builds on the open source code",
           "below, under those projects' own licenses. Generated by `scripts/third-party.py`.", ""]
    out += ["## In the app", "",
            "| Package | Version | License |", "| --- | --- | --- |"]
    licenses = {
        "libghostty-spm": "MIT. Builds [Ghostty](https://github.com/ghostty-org/ghostty) (MIT) and the libraries "
                          "Ghostty links, under their own licenses: see Ghostty's repository",
        "MSDisplayLink": "MIT",
        "Sparkle": "MIT, with notices for code it includes: see its [LICENSE](https://github.com/sparkle-project/Sparkle/blob/2.x/LICENSE)",
    }
    for url, version in swift_packages():
        name = url.rstrip("/").removesuffix(".git").split("/")[-1]
        out.append(f"| [{name}]({url.removesuffix('.git')}) | {version} | {licenses.get(name, 'see its repository')} |")
    out += ["", "## Files carried in this repository", "",
            "| What | Where | License |", "| --- | --- | --- |"]
    for what, where, lic in BUNDLED:
        out.append(f"| {what} | `{where}` | {lic} |")
    crates = rust_crates()
    out += ["", f"## Rust crates ({len(crates)})", "",
            "Each crate's full license text is in its source, on crates.io and in its repository.", "",
            "| Crate | Version | License |", "| --- | --- | --- |"]
    for name, version, lic, repo in crates:
        label = f"[{name}]({repo})" if repo else name
        out.append(f"| {label} | {version} | {lic} |")
    open(OUT, "w").write("\n".join(out) + "\n")
    print(f"wrote {OUT}: {len(crates)} crates")


main()
